trigger:
- master

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- script: dotnet restore StringExtensionsLib/StringExtensionsLib.csproj
  displayName: 'Restore'

- script: dotnet build StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet pack StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"
  displayName: 'Pack NuGet package'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate to Azure Artifacts'

- script: nuget push "$(Build.ArtifactStagingDirectory)\*.nupkg" -Source "https://pkgs.dev.azure.com/ian-devops/StringExtensionsLibProject/_packaging/stringextensions-feed/nuget/v3/index.json" -ApiKey az -SkipDuplicate
  displayName: 'Push package to Azure Artifacts'