trigger:
- master

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- script: dotnet restore StringExtensionsLib.sln
  displayName: 'Restore'

- script: dotnet build StringExtensionsLib.sln --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet pack StringExtensionsLib/StringExtensionsLib.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack NuGet package'